spring:
  application:
    name: Plitche-Univ
  datasource:
    url: jdbc:h2:tcp://localhost/~/univ
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
       ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

  devtools:
    restart:
      enabled: false # 자동 재시작 비활성화
      additional-paths: # 재시작 트리거가 되는 폴더 지정
        - src/main/java
      exclude: # 재시작 제외 폴더 설정
        - static/**
        - public/**

logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.type: trace

