spring:
  application:
    name: Plitche-Univ
  datasource:
    url: jdbc:h2:tcp://localhost/~/univ
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
       ddl-auto: create
#      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
#    org.hibernate.type: trace
